### ISSUE TITLE
App crashes when picked file in android 11 and higher devices

### ISSUE THREAD

**Issue by ALFIN-TT** [fbiego/ESP32_BLE_OTA_Android#8]
2022-07-07 19:21:13.009 24256-24256/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fbiego.ota, PID: 24256
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=56, result=-1, data=Intent { dat=content://com.android.externalstorage.documents/document/primary:OTA/esp32_v1.2.ino_OTA_advertise_FBIEGO.bin flg=0x1 }} to activity {com.fbiego.ota/com.fbiego.ota.MainActivity}: java.io.FileNotFoundException: /storage/emulated/0/OTA/esp32_v1.2.ino_OTA_advertise_FBIEGO.bin: open failed: EACCES (Permission denied)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5098)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5139)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2104)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:7861)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
     Caused by: java.io.FileNotFoundException: /storage/emulated/0/OTA/esp32_v1.2.ino_OTA_advertise_FBIEGO.bin: open failed: EACCES (Permission denied)
        at libcore.io.IoBridge.open(IoBridge.java:492)
        at java.io.FileInputStream.<init>(FileInputStream.java:160)
        at com.fbiego.ota.MainActivity.saveFile(MainActivity.kt:596)
        at com.fbiego.ota.MainActivity.onActivityResult(MainActivity.kt:698)
        at android.app.Activity.dispatchActivityResult(Activity.java:8476)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5091)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5139) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2104) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:236) 
        at android.app.ActivityThread.main(ActivityThread.java:7861) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967) 
     Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Linux.open(Native Method)

**Comment by fbiego** [comment]
The file picker is only implemented for previous version of Android.
You can try the playstore version which uses Storage Access Framework
